services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CONTENT_SAFETY_KEY=${CONTENT_SAFETY_KEY}
      - CONTENT_SAFETY_ENDPOINT=${CONTENT_SAFETY_ENDPOINT}
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
